# D24魔法方法,异常

## 一、内置方法(魔法方法)

- 魔法方法:前后都有双下划线的方法
- 特点:在遇到某些情况时自动调用,可以重写,在某些特殊情况下被python调用,可以定义自己想要的行为,而这一切都是自动发生的
- __ new __ (cls,):在一个类实例化对象时所调用的第一个方法,用于申请空间,类调用
- __ init __ (self,):构造器,类实例化对象时调用的第二个方法,用于初始化实例对象
- __ del __(self):析构器,当一个实例被销毁的时候调用(建议不要重写),这个方法比较特殊,即使重写了也依然会执行删除的操作,并且在函数操作结束后会自动执行
- __ len __:调用len()时自动调用该方法,返回值必须为int类型
- __ hash __:调用hash()(用于获取一个不可变数据类型的哈希值)时自动调用该方法,是一种消息摘要算法
- __ str __:打印对象时调用
- __ eq __:比较两个对象时调用

## 二、异常处理

- 异常:本身是一个事件,该事件可能会在程序执行过程中发生,从而影响程序的正常执行

- 发生异常的两种方式:

  - raise语句显式的抛出异常
  - python解释器自己检测到异常并引发它

- 一般情况下,python无法正常处理程序时就会发生异常

- 异常也是一个对象,表示一个错误

- 当python程序发生异常时我们需要捕获处理它,否则程序会终止执行

- 常见异常种类:

  • SyntaxError语法错误
  • IndentationError多打一个空格
  • NameError 使用一个还未被赋予对象的变量
  • TypeError 传入对象类型与要求的不符合 （int + str）
  • IOError 输入/输出异常；基本上是无法打开文件
  • ImportError 无法引入模块或包；基本上是路径问题或名称错误
  • IndexError 下标索引超出序列边界
  • KeyError 试图访问字典里不存在的键

- 处理异常:

  - 使用try except捕捉异常,也就是说遇到这个异常就进入except的分支,使程序不会崩溃

    ```
    try:
        print(a/b)            #被检测的代码块	
    except ZeroDivisionError:
        b = int(input("ccc"))    #try一旦检测到异常,就执行这个位置的逻辑
        print(a/b)
    ```

- 过程

  • 如果你不想在异常发生时结束你的程序，只需在try里捕获它
  • 首先，执行 try 子句 （在 try 和 except 关键字之间的部分）
  • 如果没有异常发生，except 子句在 try 语句执行完毕后就被忽
  略了
  • 如果在 try 子句执行过程中发生了异常，那么该子句其余的部
  分就会被忽略
  • 如果异常匹配于 except 关键字后面指定的异常类型，就执行对
  应的 except 子句。然后继续执行 try 语句之后的代码

-  多种捕获（多分支）
  • except可以指定捕获的类型,捕获多种异常
  • 多个except即可,但是之后最多匹配一个异常
  • 如果没有任何一个except语句捕获这异常,则该异常向外抛出

  ```
  try:
  	print(1/0)
  	raise FileNotFoundError
  except ZeroDivisionError:
  	print("0不能作为除数")
  except FileNotFoundError:
  	print("异常 2")
  print("后续语句")
  ```

-  except ... as ...
  • 使用exception as e:查看异常，以及是否按要求捕获到

  ```
  try:
  print(1/0)
  raise FileNotFoundError
  except Exception as e: #万能异常
  print(e)
  输出结果:
  division by zero   #这时异常的显示信息
  ```

- • 如果想要的效果是，无论出现什么异常，我们统一丢弃，或者使
  用同一段代码逻辑去处理他们，只有一个Exception就足够了
  • 如果想要的效果是，对于不同的异常定制不同的处理逻辑，需要
  用到多分支

  • 多分支+万能异常
  • 发生的异常中，有一些异常是需要不同的逻辑处理的，剩下的异常统一处理掉即可

  ```
  dic = {1: login,2: register,3: dariy,4: article,5: comment,}
  print('''欢迎访问博客园系统：
      1，登录
      2，注册
      3，访问日记页面
      4，访问文章页面
      5，访问评论页面''')
  try:
      choice = int(input('请输入：'))
      dic[choice]()
  except ValueError:
  	print('请输入数字....')
  except KeyError:
  	print('您输入的选项超出范围...')
  except Exception as e:
  	print(e)
  ```

- try...except...else组合
  与循环中的else类似，try代码中，只要出现了异常，则不会执行else语
  句，如果不出现异常，则执行else语句
  伪代码：

  ```
  try:
  	print('扣第一个人钱')
  	print('给第二个人加钱')
  except ValueError:
  	print('必须输入数字。。。')
  else:
  	print('转账成功')
  ```

- try...excet...finally组合:
   finally:最后一定要执行的语句块

  ```
  try:
  	dic = {'name': 'shang'}
  	print(dic[1])
  except KeyError:
  	print('出现了keyError错误....')
  finally:
  	print('正常执行')
  ```

- 如果出现异常但是没有成功捕获，finally会在异常发生之前执行

  ```
  try:
  	dic = {'name': 'shang'}
  	print(dic[1])
  except NameError:
  	print('出现了NameError错误....')
  finally:
  	print('执行结束')			
  ```

  如果try用于函数中,finally也会在return前执行,while循环中的break前也会执行finally里的语句
  
  ```
  def a():
      try:
          print(a)
          return 1
      finally:
          print(2)
  c = a()
  输出结果:
  <function a at 0x03BDAF60>
  2
  ```
  
- 主动发出异常:

   - raise 错误

- 断言:

   - 表示一种强硬的态度，只要assert后面的代码不成立，直接报错，下面
      的代码就不让你执行

   ```
   assert 1>2
   print("a")
   输出结果:
   a
   ```

- 自定义异常:

   如果以后你在工作中，出现了某种异常无法用已知的错误类型捕获（万
   能异常只能捕获python中存在的异常），那么你就可以尝试自定义异常，
   只要继承BaseException类即可

   ```
   class aaError(Exception):
       def __init__(self,n):
           self.n = n
       value = "aa错误"
   
   try:
       a = input("a")
       b = input("b")
       if a>b:
           raise aaError("ggg")
   except aaError as e:
       print(e.value)
   输出结果:
   a2
   b1
   aa错误
   ```

   ```
   class aaError(Exception):
       def __init__(self,n):
           self.n = n
       value = "aa错误"
   
   try:
       a = input("a")
       b = input("b")
       if a>b:
           raise aaError("ggg")
   except aaError as e:
       print(e)
   输出结果:
   a2
   b1
   ggg
   
   ```

   ```
   老师例:
   class HelloError(Exception):
   	def __init__(self,n):
   		self.n=n
   try:
   	n=input("请输入数字：")
   	if not n.isdigit():
   		raise HelloError(n)
   except HelloError as hi:
   	print("HelloError：请输入字符。\n您输入的是：",hi.n)
   else:
   	print("未发生异常")
   ```

   